apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    usage: personal-applications

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-cache-db
  namespace: apps
  labels:
    app: reactive-cache-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-cache-db
  template:
    metadata:
      labels:
        app: reactive-cache-db
    spec:
      containers:
      - name: reactive-cache-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: 'reactive-cache'
        - name: POSTGRES_USER
          value: 'reactive-cache'
        - name: POSTGRES_PASSWORD
          value: ''
        - name: POSTGRES_HOST_AUTH_METHOD
          value: 'trust'

---

apiVersion: v1
kind: Service
metadata:
  name: reactive-cache-db
  namespace: apps
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: reactive-cache-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-cache-redis
  namespace: apps
  labels:
    app: reactive-cache-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-cache-redis
  template:
    metadata:
      labels:
        app: reactive-cache-redis
    spec:
      containers:
      - name: reactive-cache-redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: reactive-cache-redis
  namespace: apps
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: reactive-cache-redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-cache-worker
  namespace: apps
  labels:
    app: reactive-cache-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-cache-worker
  template:
    metadata:
      labels:
        app: reactive-cache-worker
    spec:
      containers:
      - name: reactive-cache-worker
        image: ghcr.io/parinpan/reactive-cache-worker:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: 'reactive-cache-redis.apps.svc.cluster.local'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_DB
          value: '0'
        - name: DB_HOST
          value: 'reactive-cache-db.apps.svc.cluster.local'
        - name: DB_PORT
          value: '5432'
        - name: DB_USERNAME
          value: 'reactive-cache'
        - name: DB_PASSWORD
          value: ''
        - name: DB_NAME
          value: 'reactive-cache'
        - name: build_date
          value: '{{build_date}}'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-cache-server
  namespace: apps
  labels:
    app: reactive-cache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-cache-server
  template:
    metadata:
      labels:
        app: reactive-cache-server
    spec:
      containers:
      - name: reactive-cache-server
        image: ghcr.io/parinpan/reactive-cache-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOST
          value: 'reactive-cache-redis.apps.svc.cluster.local'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_DB
          value: '0'
        - name: DB_HOST
          value: 'reactive-cache-db.apps.svc.cluster.local'
        - name: DB_PORT
          value: '5432'
        - name: DB_USERNAME
          value: 'reactive-cache'
        - name: DB_PASSWORD
          value: ''
        - name: DB_NAME
          value: 'reactive-cache'
        - name: build_date
          value: '{{build_date}}'

---

apiVersion: v1
kind: Service
metadata:
  name: reactive-cache-server-service
  namespace: apps
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: reactive-cache-server
